import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import type { ZodObject, ZodRawShape } from "zod";

export type FinanceRecord = Record<string, unknown>;
export type FinanceItem = FinanceRecord & {
  id: string;
  title: string;
  type: string;
  canonical_product_id?: string;
  resolved_canonical_product_id?: string;
  sales_verified_at?: string;
  provenance?: FinanceRecord[];
  provenance_shard?: string;
  sources?: string[];
  source_urls?: string[];
  source_basis_dates?: string[];
  capabilities?: { comparison?: string; recommendation?: string };
  comparison_approved?: boolean;
  recommendation_approved?: boolean;
  candidate_id?: string;
  option_id?: string;
  offer_id?: string;
  evidence_gate?: FinanceRecord;
};
export type FinanceArtifactSet = Partial<Record<string, unknown>>;
export type FinanceArtifactKey = "source_registry" | "source_status" | "provenance_index" | "provenance_coverage" | "relationship_index";
export type ToolResult = { structuredContent: FinanceRecord; content: Array<{ type: "text"; text: string }> };
export type SearchFilters = {
  searchType?: string;
  productKind?: string;
  recommendationStatus?: string;
  recommendationScope?: string;
  salesStatus?: string;
  applicationStatus?: string;
  provider?: string;
  region?: string;
  freshnessStatus?: string;
};
export type FinanceManifest = FinanceRecord & {
  version?: string;
  basis_date?: string;
  exports: Array<FinanceRecord & { item_count?: number }>;
  search_index?: FinanceRecord & { item_count?: number };
  quality_exports?: unknown[];
  source_registry?: unknown;
  source_status?: unknown;
  provenance_index?: unknown;
  provenance_coverage?: unknown;
  relationship_index?: unknown;
  domain_readiness?: Record<string, FinanceRecord>;
  capabilities?: { discovery?: string; comparison?: string; recommendation?: string };
};

export type ToolContext = {
  server: McpServer;
  env: Env;
  mcpResult: (payload: FinanceRecord) => ToolResult;
  financeResult: (payload: FinanceRecord) => ToolResult;
  financeSafety: (payload: FinanceRecord) => FinanceRecord;
  normalizeFinanceSnapshot: (raw?: FinanceRecord) => FinanceRecord;
  financeMetrics: (snapshot: FinanceRecord) => Record<string, FinanceRecord>;
  financeNeeds: (snapshot: FinanceRecord, metrics: Record<string, FinanceRecord>) => FinanceRecord[];
  assertFinanceSafe: (value: unknown) => void;
  financeNumber: (value: unknown, field: string, allowNegative?: boolean) => number;
  isRecord: (value: unknown) => value is FinanceRecord;
  evaluateEligibility: (item: FinanceRecord, inputs: FinanceRecord) => {
    matched_conditions: string[];
    failed_conditions: string[];
    unknown_conditions: string[];
  };
  productDomain: (item: FinanceRecord) => string | null;
  financeAuditId: (...values: unknown[]) => string;
  loadSearchItems: (env: Env) => Promise<readonly FinanceItem[]>;
  hydrateSearchItem: (env: Env, item: FinanceItem) => Promise<FinanceItem>;
  PERSONAL_FINANCE_POLICY_VERSION: string;
  ADVICE_POLICY_VERSION: string;
  STANDARD_OUTPUT_SCHEMA: ZodObject<ZodRawShape>;
  READ_ONLY_TOOL_ANNOTATIONS: Record<string, boolean>;
  dedupeProductItems: (items: readonly FinanceItem[]) => readonly FinanceItem[];
  loadDetailedItemsForDomain: (env: Env, domain: string) => Promise<readonly FinanceItem[]>;
  loadSearchIndexMetadata: (env: Env) => Promise<{ basis_date?: string }>;
  loadFinanceManifest: (env: Env) => Promise<FinanceManifest>;
  manifestChecksumContract: (manifest: FinanceRecord) => boolean;
  comparisonReleaseGate: (manifest: FinanceRecord, domain: string) => { status: "ready" | "blocked"; reasons: string[] };
  loadFinanceArtifacts: (env: Env, keys: readonly FinanceArtifactKey[]) => Promise<FinanceArtifactSet>;
  normalizeQuery: (value: string) => string;
  comparisonBlocker: (item: FinanceItem, artifacts: FinanceArtifactSet, salesVerificationTtlHours: number) => string | undefined;
  comparisonOptionCandidates: (item: FinanceItem, termMonths: number) => readonly FinanceRecord[];
  comparisonOptionBlocker: (option: FinanceRecord, domain: string, depositAmount: number | undefined, monthlyPayment: number | undefined, channels: readonly string[], savingMethod: string | undefined) => string | undefined;
  comparisonCandidate: (item: FinanceItem, option: FinanceRecord, facts: FinanceRecord, depositAmount: number | undefined, monthlyPayment: number | undefined, taxRatePercent: number) => FinanceRecord;
  reasonCounts: (excluded: readonly { readonly reason: string }[]) => Record<string, number>;
  EXCLUDED_SAMPLE_LIMIT: number;
  comparisonBlockers: (domain: string, summary: Record<string, number>) => readonly FinanceRecord[];
  domainMatches: (item: FinanceItem, domain: string) => boolean;
  COMPARISON_ENGINE_VERSION: string;
  jsonText: (value: unknown) => string;
  discoveryDomainForQuery: (query: string) => string | undefined;
  SUPPORT_INTENT_RE: RegExp;
  loadSearchItemsForQuery: (env: Env, query: string, type?: string, searchType?: string, productKind?: string) => Promise<readonly FinanceItem[]>;
  isNamedProductQuery: (query: string) => boolean;
  strictNamedProductPayload: (query: string, items: readonly FinanceItem[], limit: number, env: Env) => FinanceRecord | undefined;
  enrichSearchPayload: (payload: FinanceRecord, items: readonly FinanceItem[], artifacts: FinanceArtifactSet) => FinanceRecord;
  isDiscoveryQuery: (query: string) => boolean;
  discoveryPayload: (query: string, items: readonly FinanceItem[], limit: number, artifacts?: FinanceArtifactSet) => FinanceRecord;
  SEARCH_TYPE_GROUPS: Record<string, ReadonlySet<string>>;
  inferredTypesForQuery: (query: string) => Set<string> | null;
  supportRegionForQuery: (query: string) => string | undefined;
  inferredSearchTypeForQuery: (query: string) => string | undefined;
  matchesSearchFilters: (item: FinanceItem, filters: SearchFilters, artifacts: FinanceArtifactSet) => boolean;
  matchesSupportRegion: (item: FinanceItem, region?: string) => boolean;
  matchesSupportIntent: (item: FinanceItem, query: string) => boolean;
  isPubliclySearchable: (item: FinanceItem) => boolean;
  scoreItem: (item: FinanceItem, query: string) => number;
  matchReasons: (item: FinanceItem, query: string) => string[];
  supportMatchTier: (item: FinanceItem, query: string) => "exact" | "partial" | "related" | undefined;
  itemUrl: (env: Env, itemId: string) => string;
  sourceHealth: (item: FinanceItem, artifacts?: FinanceArtifactSet) => FinanceRecord;
  supportParsedQuery: (query: string, region?: string) => FinanceRecord;
  supportExcludedSummary: (items: readonly FinanceItem[], query: string, region: string | undefined, filters: SearchFilters, allowedTypes: ReadonlySet<string> | null, resultIds: ReadonlySet<string>, limit: number) => Record<string, number>;
  fetchItemGraph: (env: Env, id: string) => Promise<{ item: FinanceItem; itemsById: Map<string, FinanceItem> }>;
  resolveItemId: (id: string) => string;
  sourceItems: (item: FinanceItem, itemsById: Map<string, FinanceItem>) => readonly FinanceItem[];
  publicProvenance: (item: FinanceItem, artifacts: FinanceArtifactSet) => { entries: FinanceRecord[]; unresolvedCount: number };
  loadProvenanceShard: (env: Env, manifest: FinanceRecord, shardId: string) => Promise<unknown | undefined>;
  artifactErrors: () => FinanceRecord[];
  loadFinanceArtifact: (env: Env, key: FinanceArtifactKey, manifest?: FinanceManifest) => Promise<unknown | undefined>;
  coverageReport: (value: unknown) => FinanceRecord | null;
  runtimeMetadata: (env: Env, manifest: FinanceManifest, metadata: { basis_date?: string }) => Promise<FinanceRecord>;
};
