interface Env {
  FINANCE_MANIFEST_URL: string;
  FINANCE_WEB_BASE_URL: string;
  OPENAI_APPS_CHALLENGE_TOKEN?: string;
  RUNTIME_VERSION?: string;
  DEPLOYMENT_COMMIT?: string;
  OWNER_PILOT_ENABLED?: string;
  OWNER_PILOT_SESSION_SECRET?: string;
  BUILD_TIMESTAMP?: string;
  ARTIFACT_GENERATION?: string;
}
