export type HealthEnv = { RUNTIME_VERSION?: string; DEPLOYMENT_COMMIT?: string; BUILD_TIMESTAMP?: string; ARTIFACT_GENERATION?: string; FINANCE_MANIFEST_URL?: string };
const record = (value: unknown): Record<string, unknown> => value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {};
const liveCurrent = (live: Record<string, unknown>, policy: Record<string, unknown>, deploymentCommit?: string, expectedGenerationId?: string, now = Date.now()) => {
  const checkedAt = Date.parse(String(live.checked_at ?? ""));
  const age = now - checkedAt;
  const ttlHours = Number(policy.freshness_ttl_hours ?? 24);
  return live.status === "current" && live.mode === (policy.required_mode ?? "live") && live.test_count === (policy.required_count ?? 120) && live.passed_count === (policy.required_count ?? 120) && live.failed_count === 0 && (live.skipped_count ?? 0) === 0 && Number.isFinite(checkedAt) && age >= 0 && age <= ttlHours * 60 * 60 * 1000 && typeof live.manifest_checksum === "string" && typeof live.loaded_index_checksum === "string" && typeof live.deployment_commit === "string" && live.deployment_commit !== "unknown" && (!deploymentCommit || live.deployment_commit === deploymentCommit) && (!expectedGenerationId || live.generation_id === expectedGenerationId);
};

export function livenessPayload(env: HealthEnv, manifestUrl: string, details: Record<string, unknown> = {}) { return { name: "finance", status: "ok", runtime_version: env.RUNTIME_VERSION ?? "openfin-mcp-unknown", deployment_commit: env.DEPLOYMENT_COMMIT ?? "unknown", build_timestamp: env.BUILD_TIMESTAMP ?? null, artifact_generation: env.ARTIFACT_GENERATION ?? null, mcp_endpoint: "/mcp", finance_manifest_url: manifestUrl, ...details }; }

export function readinessPayload(input: { env: HealthEnv; manifest?: Record<string, unknown>; metadata?: Record<string, unknown>; artifactsLoaded: boolean; checksumVerified: boolean; cacheAgeMs?: number; manifestUrl: string }) {
  const manifest = input.manifest ?? {};
  const live = record(manifest._live_regression ?? manifest.openfin_120_live_regression);
  const domain = record(manifest.domain_readiness);
  const coreReady = input.artifactsLoaded && input.checksumVerified && Boolean(input.metadata);
  const compare = (name: string) => record(domain[name]).status === "limited_public_ready" ? "limited" : "blocked";
  const manifestCapabilities = record(manifest.capabilities);
  const capabilities = { core: coreReady ? "ready" : "blocked", search: manifestCapabilities.search ?? (coreReady ? "ready" : "blocked"), fetch: coreReady ? "ready" : "blocked", discover: manifestCapabilities.discovery ?? (coreReady ? "ready" : "blocked"), source_freshness: manifest.source_freshness_status === "ready" ? "ready" : "degraded", compare_deposit: compare("deposit"), compare_saving: compare("saving"), shadow: manifestCapabilities.shadow ?? "blocked", owner_pilot: manifestCapabilities.owner_pilot ?? "blocked", recommendation: manifestCapabilities.recommendation ?? "blocked" };
  return { name: "finance", status: coreReady ? "ready" : "degraded", ready: coreReady, capabilities, service_availability: manifest.service_availability ?? "degraded", runtime_version: input.env.RUNTIME_VERSION ?? "openfin-mcp-unknown", deployment_commit: input.env.DEPLOYMENT_COMMIT ?? "unknown", build_timestamp: input.env.BUILD_TIMESTAMP ?? null, artifact_generation: input.env.ARTIFACT_GENERATION ?? null, source_head_commit: manifest.source_head_commit ?? null, release_candidate_commit: manifest.release_candidate_commit ?? null, production_commit: manifest.production_commit ?? null, production_deployed_at: manifest.production_deployed_at ?? null, production_generation: manifest.generation_id ?? null, pages_generation: manifest.generation_id ?? null, worker_generation: input.env.ARTIFACT_GENERATION ?? manifest.generation_id ?? null, release_pointer: manifest.current_release ?? null, mcp_endpoint: "/mcp", finance_manifest_url: input.manifestUrl, manifest_version: manifest.version ?? null, manifest_checksum: manifest.manifest_checksum ?? null, generation_id: manifest.generation_id ?? null, artifact_contract: manifest.artifact_contract ?? null, source_freshness_status: manifest.source_freshness_status ?? "degraded", comparison_status: manifest.comparison_status ?? "unknown", recommendation_status: manifest.recommendation_status ?? "unknown", recommendation_enabled: manifest.recommendation_enabled ?? false, blocking_reasons: manifest.blocking_reasons ?? ["MANIFEST_UNAVAILABLE"], recommendation_blocking_reasons: manifest.recommendation_blocking_reasons ?? [], live_regression: Object.keys(live).length ? live : null, search_available: Boolean(input.metadata), loaded_index_checksum: input.metadata?.export_checksum ?? null, loaded_item_count: input.metadata?.item_count ?? null, cache_age_ms: input.cacheAgeMs ?? null, artifacts_loaded: input.artifactsLoaded, checksum_verified: input.checksumVerified };
}
